<?php
/**
 * @file
 *
 * 实现 WeChat Server 功能
 *
 */

/**
 * Implements hook_node_load()
 */
function cndevel_wechat_node_load($nodes, $types){
    watchdog("cnDevel WeChat Module", "pre-handle before node load");
}

/**
 * Implements hook_menu().
 *
 * @see module_invoke_all()
 * @link http://api.drupal.org/api/group/hooks/7
 */
function cndevel_wechat_menu() {

    watchdog("cnDevel WeChat Module", "menu configurations have been read...");

    $items['admin/config/cndevel'] = array(
        'title' => 'cnDevel Modules',
        'description' => 'Adjust cnDevel modules\' options.',
        'position' => 'right',
        'weight' => -99,
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array('administer site configuration'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );
    $items['admin/config/cndevel/wechat-service'] = array(
        'title' => 'WeChat: Service Account',
        'description' => 'Set parameters of Service Account for WeChat module.',
        'page callback' => 'drupal_get_form',                                       // 访问此配置时，此函数会被调用
        'page arguments' => array('cndevel_wechat_service_admin_settings'),         // 此值会被当参数传入
        'access arguments' => array('administer site configuration'),               // 用户需要此权限才能看到这个菜单
        'type' => MENU_NORMAL_ITEM,
        'file' => 'cndevel_wechat.admin.inc',
    );
    $items['admin/config/cndevel/wechat-enterprise'] = array(
        'title' => 'WeChat: Enterprise Account',
        'description' => 'Set parameters of Enterprise Account for WeChat module.',
        'page callback' => 'drupal_get_form',                                       // 访问此配置时，此函数会被调用
        'page arguments' => array('cndevel_wechat_enterprise_admin_settings'),      // 此值会被当参数传入
        'access arguments' => array('administer site configuration'),               // 用户需要此权限才能看到这个菜单
        'type' => MENU_NORMAL_ITEM,
        'file' => 'cndevel_wechat.admin.inc',
    );
    return $items;
}

/**
 * 输出日志确认用户的确已从 WeChat 登陆
 *
 * Implements hook_user_login().
 */
function cndevel_wechat_user_login(&$edit, $account){

    watchdog("cnDevel WeChat Module", "user login from WeChat...");

}

/**
 * 输出日志确认新内容已发布至 WeChat
 *
 * Implements hook_node_insert().
 */
function cndevel_wechat_node_insert($node){

    watchdog("cnDevel WeChat Module", "New content has been released to WeChat...");

}


/**
 * 定义 Actions
 *
 * Implements hook_action_info().
 */
function cndevel_wechat_action_info() {
    return array(
        'cndevel_log_action' => array(
            'type' => 'system',  // system, user, node, comment, taxonomy
            'label' => t('log information for key steps.'),
            'configurable' => FALSE,
            'triggers' => array('node_view', 'cron', 'node_update', 'user_insert'),  // Set to 'any' to support all triggers.
        ),
    );
}


/**
 * 日志输出
 *
 *
 */
function cndevel_log_action(){
    watchdog("cnDevel Module", "Log action has been triggered...");
}




